const styles = {
  navbar: "fixed top-0 left-0 w-full h-auto z-50 p-4 bg-white  border-red-500",
  floor1: "flex justify-between items-center",
  logoContainer: "flex items-center",
  logo: "w-12 h-12",
  logoText: "ml-4 text font-bold hidden md:block",
  dropdownContainer: "space-x-4 mr-32 hidden md:flex hidden  md:hidden lg:flex gap-4",
  floor2: "flex justify-normal mt-4",
  searchBar: "flex  justify-center  relative ml-16 lg:ml-42  md:ml-5 lg:w-112 md:w-60 w-12  ",
  search: "absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 mr-60 hidden md:flex lg:flex",
  searchInput: "border-2 border-black rounded-full w-112  h-10 px-2 md:px-10 lg:px-10 text-sm",
  star: "border border-black h-10 w-fit rounded-full justify-centre relative cursor-pointer ml-16 hidden md:flex md:ml-10",
  
  starIcon: "mt-2 ml-2",
  starText: "text-sm text-black mt-2 ml-2 mr-2 ",
  headphone: "hidden md:hidden lg:flex w-fit border border-black h-10 rounded-full relative flex justify-around  cursor-pointer  md:ml-2 lg:ml-5",
  headphone2: "flex md:hidden w-44 border border-black h-10 rounded-full relative flex justify-around  cursor-pointer ",
  headphoneText: "text-sm text-black mt-2 mr-2",
  headphpneIcon: "mt-2 ml-2",
  login: " lg:flex w-24 border border-black h-10 rounded-full justify-centre relative bg-red-800  relative group cursor-pointer lg:ml-5 ml-24 md:ml-2",
  loginIcon: "md:ml-5 lg:ml-5 ml-2 mt-2 md:mt-1.5 lg:mt-0",
  loginText: "ml-1 text-white mt-1 md:mt-1.5 lg:mt-0",
  headphonedropDown: "absolute bg-white border border-gray-300 shadow-md mt-10 w-80",
  headphonedropDownul: "list-none m-0 p-0",
  hdl1: "px-4 py-2 cursor-pointer hover:bg-gray-100",
  hdl1outer: "flex justify-start border-b-2 p-2 space-x-4",
  hdl1inner: "flex flex-col justify-center",
  hdl1innertext: "text-sm font-semibold text-red-800",
  hdl1innertext2: "text-xs text-gray-500",
  hdl2: "px-4 py-1 cursor-pointer hover:bg-gray-100",
  hdl2outer: "flex justify-start p-2 space-x-4",
  hdl2inner: "flex flex-col justify-center",
  hdl2innertext: "text-sm font-semibold text-red-800",
  hdl2innertext2: "text-xs text-gray-500",
  logindropDown: "absolute left-0 bg-white border border-gray-300 shadow-lg rounded-lg mt-10 w-80 h-80 z-50",
  ldouter: "px-4 py-2 text-sm h-24 text-gray-700 mb-24",
  ldoutertext: "text-xl text-red-800 mt-5 mb-2",
  ldoutertext2: "text-black mb-2",
  ldinner: "flex w-64 border border-black h-10 rounded-full justify-center mt-5 bg-red-800 mr-44 relative group cursor-pointer",
  ldinnerIcon: "mt-2.5 ml-5",
  ldinnerIconbutton: "text-white ml-2",
  ldul: "list-none m-0 p-0",
  ldl1: "mt-5 cursor-pointer hover:bg-gray-100",
  ldl1outer: "flex justify-between p-2 space-x-4 bg-gray-200 border-b-2 border-gray-400",
  ldl1inner: "flex flex-col justify-center",
  ldl1innertext: "text-sm font-sm text-black",
  ldl1innertext2: "text-xl text-red-800",
  ldl1Icon: "mt-2",
  ldl2: "cursor-pointer hover:bg-gray-100",
  ldl2outer: "flex justify-between p-2 space-x-4 bg-gray-200 w-80",
  ldl2inner: "flex flex-col justify-center",
  ldl2innertext: "text-sm font-sm text-black",
  ldl2innertext2: "text-xl text-red-800",
  ldl2Icon: "mt-2"
};

export default styles;
